### ISSUE TITLE
language-info and language-refresh commands

### ISSUE THREAD

**Issue by frederickjh** [dawehner/drush_language#15]
Hi!
Are there plans to have the language-info and language-refresh commands in this version of the drush_language extension?
Thanks!
Frederick

**Comment by dawehner** [comment]
Well, the github repo is deprecated and instead the drupal.org project
should be used

**Comment by frederickjh** [comment]
OK, then I guess you are saying I should file this in the Drupal.org issue queue.
Done. [drupl.org - drush_language issue - language-info and language-refresh commands](https://www.drupal.org/node/2856893)

**Comment by dawehner** [comment]
Yeah, thank you
